Importing the libraries

In [134]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score

Importing the dataset

In [135]:
#laoding the dataset
dataset = pd.read_csv('/content/virat_kohli_odi_century_progression.csv')

In [136]:
print(dataset.head)

<bound method NDFrame.head of     year  matches  centuries
0   2008        5          0
1   2009       20          1
2   2010       45          3
3   2011       82          8
4   2012      119         13
5   2013      146         17
6   2014      169         21
7   2015      183         23
8   2016      194         25
9   2017      208         32
10  2018      223         38
11  2019      242         43
12  2020      248         43
13  2021      254         43
14  2022      265         45
15  2023      292         50>

In [137]:
import pandas as pd

# Create new rows for 2024 and 2025 with placeholder values
new_data = pd.DataFrame({
    'year': [2024, 2025],
    'matches': [295, 308],
    'centuries': [51, 54],

})

# Concatenate the new data with the existing dataset
dataset = pd.concat([dataset, new_data], ignore_index=True)

print("Dataset after adding rows for 2024 and 2025:")
display(dataset.tail())

Dataset after adding rows for 2024 and 2025:

    year  matches  centuries
13  2021      254         43
14  2022      265         45
15  2023      292         50
16  2024      295         51
17  2025      308         54

In [138]:
dataset.rename(columns={'centuries':'ODI Centuries'}, inplace=True)

In [139]:
dataset.head()

   year  matches  ODI Centuries
0  2008        5              0
1  2009       20              1
2  2010       45              3
3  2011       82              8
4  2012      119             13

In [140]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           18 non-null     int64
 1   matches        18 non-null     int64
 2   ODI Centuries  18 non-null     int64
dtypes: int64(3)
memory usage: 564.0 bytes

In [141]:
dataset.shape

(18, 3)

// BF' stands for 'Balls Faced', which represents the number of deliveries a batsman has received.

In [142]:
dataset.describe()

              year     matches  ODI Centuries
count    18.000000   18.000000      18.000000
mean   2016.500000  183.222222      28.333333
std       5.338539   95.494105      18.365569
min    2008.000000    5.000000       0.000000
25%    2012.250000  125.750000      14.000000
50%    2016.500000  201.000000      28.500000
75%    2020.750000  252.500000      43.000000
max    2025.000000  308.000000      54.000000

In [143]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           18 non-null     int64
 1   matches        18 non-null     int64
 2   ODI Centuries  18 non-null     int64
dtypes: int64(3)
memory usage: 564.0 bytes

In [144]:
dataset['Total Centuries'] = (dataset['ODI Centuries'] + 31).astype(int)
print("The 'Century' column has been created with numerical values (1 for century, 0 otherwise).")

The 'Century' column has been created with numerical values (1 for century, 0 otherwise).

In [145]:
dataset.corr()

                     year   matches  ODI Centuries  Total Centuries
year             1.000000  0.976625       0.989938         0.989938
matches          0.976625  1.000000       0.983699         0.983699
ODI Centuries    0.989938  0.983699       1.000000         1.000000
Total Centuries  0.989938  0.983699       1.000000         1.000000

In [146]:
X = dataset[['Total Centuries']]
Y = dataset[['year', 'matches', 'ODI Centuries']]

print("Head of new X DataFrame:")
print(X.head())
print("\nHead of new Y DataFrame:")
print(Y.head())

Head of new X DataFrame:
   Total Centuries
0               31
1               32
2               34
3               39
4               44

Head of new Y DataFrame:
   year  matches  ODI Centuries
0  2008        5              0
1  2009       20              1
2  2010       45              3
3  2011       82              8
4  2012      119             13

In [147]:
print(X)
print(Y)

    Total Centuries
0                31
1                32
2                34
3                39
4                44
5                48
6                52
7                54
8                56
9                63
10               69
11               74
12               74
13               74
14               76
15               81
16               82
17               85
    year  matches  ODI Centuries
0   2008        5              0
1   2009       20              1
2   2010       45              3
3   2011       82              8
4   2012      119             13
5   2013      146             17
6   2014      169             21
7   2015      183             23
8   2016      194             25
9   2017      208             32
10  2018      223             38
11  2019      242             43
12  2020      248             43
13  2021      254             43
14  2022      265             45
15  2023      292             50
16  2024      295             51
17  2025      308             54

Train and Test split

In [148]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.1, random_state=1)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of Y_train: {Y_train.shape}")
print(f"Shape of Y_test: {Y_test.shape}")

Shape of X_train: (16, 1)
Shape of X_test: (2, 1)
Shape of Y_train: (16, 3)
Shape of Y_test: (2, 3)

Model traing--> linearRegression

In [149]:
model = LinearRegression()
model.fit(X_train,Y_train)
print("Linear Regression model has been trained with updated X and Y variables.")

Linear Regression model has been trained with updated X and Y variables.

In [150]:
Y_pred = model.predict(X_test)
print("Predictions have been made on the test set.")

Predictions have been made on the test set.

In [151]:
X_train

    Total Centuries
13               74
2                34
14               76
7                54
15               81
4                44
1                32
10               69
0                31
17               85
16               82
9                63
8                56
12               74
11               74
5                48

In [152]:
Y_train

    year  matches  ODI Centuries
13  2021      254             43
2   2010       45              3
14  2022      265             45
7   2015      183             23
15  2023      292             50
4   2012      119             13
1   2009       20              1
10  2018      223             38
0   2008        5              0
17  2025      308             54
16  2024      295             51
9   2017      208             32
8   2016      194             25
12  2020      248             43
11  2019      242             43
5   2013      146             17

Accuracy

In [153]:
X_train_prediction = model.predict(X_train)
print("Predictions have been made on the training set.")
# For regression, accuracy_score is typically not used directly.
# Let's use r2_score for regression model evaluation.
X_train_r2 = r2_score(Y_train, X_train_prediction)
print(f"R2 Score on training set: {X_train_r2}")

Predictions have been made on the training set.
R2 Score on training set: 0.982709047683683

In [154]:
Y_test_r2 = r2_score(Y_test, Y_pred)
print(f"R2 Score on test set: {Y_test_r2}")

R2 Score on test set: 0.9195806318029441

Making the predicting system

In [158]:
input_total_centuries = 100
input_data = pd.DataFrame({'Total Centuries': [input_total_centuries]})
prediction = model.predict(input_data)
precition_df = pd.DataFrame(prediction, columns=['Year', 'Matches', 'ODI Centuries'])
print("Predicted Values:")
print(precition_df)

Predicted Values:
         Year     Matches  ODI Centuries
0  2028.23598  391.629894           69.0